# Generated by Django 4.1.1 on 2022-09-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'Article'), ('NS', 'News')], default='NS', max_length=2),
        ),
    ]
