# Generated by Django 4.1.4 on 2022-12-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('post', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='subscribers',
            field=models.ManyToManyField(to='author.author'),
        ),
    ]
