# Generated by Django 4.1.4 on 2022-12-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_postcategory_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='subscribers',
        ),
    ]
