# Generated by Django 4.1.4 on 2022-12-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_postcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcounter',
            name='date',
            field=models.DateField(),
        ),
    ]
